### ISSUE TITLE
Failure to find python library

### ISSUE THREAD

**Issue by halostatue** [halostatue/rubypython#6]
Originally reported by: **Anonymous**

----------------------------------------

Trying to use Ruby's cucumber with Python got the following error:
    
    Could not open library '/usr/lib/libpython2.6.so': /usr/lib/libpython2.6.so: cannot open shared object file: No such file or directory (LoadError)
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython/python.rb:62:in `open'
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython/python.rb:62
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython/python.rb:60:in `each'
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython/python.rb:60
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython.rb:159:in `load'
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython.rb:159:in `reload_library'
    /var/lib/gems/1.8/gems/rubypython-0.3.2/lib/rubypython.rb:76:in `start'
    /var/lib/gems/1.8/gems/cucumber-0.10.0/bin/../lib/cucumber/py_support/py_language.rb:40:in `begin_scenario'
    

Running ruby 1.8.7 + Python 2.6.6. on Ubuntu Linux i686

----------------------------------------
- Bitbucket: https://bitbucket.org/raineszm/rubypython/issue/1

**Comment by halostatue** [comment]
This is what I get for not reading the full post before I going to work. I made some changes that got RubyPython working in my Windows XP virtual machine with Python 2.7 and Ruby 1.9.2, but I see I approached it a different when than you did. If my changes don't work for you I guess we'll just merge the two until they do work. I guess part of it depends on how you installed python.

**Comment by halostatue** [comment]
Pull Request with super simple support that is enough to get by with. https://github.com/halostatue/rubypython/pull/1

**Comment by halostatue** [comment]
Fixed as of <<changeset c957e2a4b4f7>>.
