### ISSUE TITLE
Uncaught exception: :pointer argument is not a valid pointer

### ISSUE THREAD

**Issue by halostatue** [halostatue/rubypython#7]
Uncaught exception: :pointer argument is not a valid pointer
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:94:in `PyLong_FromLong'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:94:in `rtopBignum'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:180:in `rtopObject'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:67:in `block in rtopHash'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:65:in `each'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:65:in `rtopHash'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/conversion.rb:176:in `rtopObject'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/pyobject.rb:71:in `initialize'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/rubypyproxy.rb:178:in `new'
	C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubypython-0.6.3/lib/rubypython/rubypyproxy.rb:178:in `method_missing'

**Comment by peter-wangxu** [comment]
This should be addressed in commit 48d97d424ef54ff39c7c37c0908d82c66de9350a
